# Generated by Django 5.1.5 on 2025-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
    ]
